### ISSUE TITLE
git cloned this project and got this error on gulp package and gulp build

### ISSUE THREAD

**Issue by cpluceDev** [MakingThingsWorkToronto/mtw-search-extensibility#1]
[16:57:54] [tsc] typescript version: 3.3.4000
[16:57:54] Finished subtask 'copy-static-assets' after 1.69 s
[16:58:03] Error - [tsc] src/components/ClientAppLinkComponent/ClientAppLinkComponent.tsx(5,20): error TS2307: Cannot find module './ClientAppComponent.module.scss'.
[16:58:04] Error - 'tsc' sub task errored after 9.39 s
 exited with code 2
[16:58:04] 'bundle' errored after 11 s
[16:58:04]
[16:58:04] ==================[ Finished ]==================
Error - [tsc] src/components/ClientAppLinkComponent/ClientAppLinkComponent.tsx(5,20): error TS2307: Cannot find module './ClientAppComponent.module.scss'.
Error - 'tsc' sub task errored after 9.39 s
 exited with code 2

**Comment by thastarkmtw** [comment]
Just pushed the latest code. A pull should resolve that for you!

Let me know and I will close. Thanks for testing!

**Comment by cpluceDev** [comment]
> git pull https://github.com/MakingThingsWorkToronto/mtw-search-extensibility.git
i tried this. From https://github.com/MakingThingsWorkToronto/mtw-search-extensibility
 * branch            HEAD       -> FETCH_HEAD
Already up to date. 

didnt work.  i guess i could downlaod everything again or  am i doing something wrong with the pull

**Comment by thastarkmtw** [comment]
Whoops - I pushed to the wrong branch!  Please retry!

**Comment by cpluceDev** [comment]
[17:29:19] Using gulpfile ~\Documents\github\PnPModernSearch\mtw-search-extensibility\gulpfile.js
[17:29:19] Starting gulp
[17:29:19] Starting 'package-solution'...
[17:29:19] Starting subtask 'configure-sp-build-rig'...
[17:29:19] Finished subtask 'configure-sp-build-rig' after 4.63 ms
[17:29:19] Starting subtask 'package-solution'...
[17:29:19] Verifying configuration...
[17:29:19] Error - Error: The webparts manifests list is empty. Please ensure you have done a build and that your config file is pointed at the correct folder.
    at Object.createPackage [as default] (C:\Users\11111\Documents\github\PnPModernSearch\mtw-search-extensibility\node_modules\@microsoft\sp-build-core-tasks\lib\packageSolution\packageSolution\createPackage.js:25:19)
    at DestroyableTransform.gulp.src.pipe.through2.obj [as _flush] (C:\Users\11111\Documents\github\PnPModernSearch\mtw-search-extensibility\node_modules\@microsoft\sp-build-core-tasks\lib\packageSolution\PackageSolutionTask.js:135:36)
    at DestroyableTransform.prefinish (C:\Users\11111\Documents\github\PnPModernSearch\mtw-search-extensibility\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:138:10)
    at DestroyableTransform.emit (events.js:198:13)
    at prefinish (C:\Users\11111\Documents\github\PnPModernSearch\mtw-search-extensibility\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:619:14)
    at finishMaybe (C:\Users\11111\Documents\github\PnPModernSearch\mtw-search-extensibility\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:627:5)
    at endWritable (C:\Users\11111\Documents\github\PnPModernSearch\mtw-search-extensibility\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (C:\Users\11111\Documents\github\PnPModernSearch\mtw-search-extensibility\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:594:41)
    at DestroyableTransform.onend (C:\Users\11111\Documents\github\PnPModernSearch\mtw-search-extensibility\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at Object.onceWrapper (events.js:286:20)
    at DestroyableTransform.emit (events.js:203:15)
    at C:\Users\11111\Documents\github\PnPModernSearch\mtw-search-extensibility\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by cpluceDev** [comment]
i also noticed this feature is for Tested/Supported for PnP Modern Search >3.10

mine says this: 

![appver](https://user-images.githubusercontent.com/25770942/92978278-f4389300-f454-11ea-9ed0-27d0937cf80e.PNG)
![modernVer](https://user-images.githubusercontent.com/25770942/92978280-f4d12980-f454-11ea-95a6-65958e573d90.PNG)

any issues?

**Comment by thastarkmtw** [comment]
Just run the "gulp bundle" before you run "gulp package-solution" and it should work fine.

No issue with using 3.15.1.0

**Comment by cpluceDev** [comment]
ah i fixed it. i had to do a gulp build than gulp package

**Comment by cpluceDev** [comment]
thanks for all the help and providing this solution. hope it works. will test it out
